production_checklist.admin_config:
  path: '/admin/config/production_checklist/checklist'
  defaults:
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
    _title: 'Production Checklist'
  requirements:
    _permission: 'administer site configuration' # @todo review permission
  options:
    _admin_route: TRUE

production_checklist.settings:
  path: '/admin/config/production_checklist/settings'
  defaults:
    _form: '\Drupal\production_checklist\Form\SettingsForm'
    _title: 'Production Checklist settings'
  requirements:
    _permission: 'administer site configuration' # @todo review permission
  options:
    _admin_route: TRUE

production_checklist.sections:
  path: '/admin/config/production_checklist/sections'
  defaults:
    _form: '\Drupal\production_checklist\Form\SectionsForm'
    _title: 'Production Checklist sections'
  requirements:
    _permission: 'administer site configuration' # @todo review permission
  options:
    _admin_route: TRUE

production_checklist.sections.confirm:
  path: '/admin/config/production_checklist/section_items/delete/{sections}'
  defaults:
    _form: '\Drupal\production_checklist\Form\DeleteSectionItemsForm'
    _title: 'Confirm delete section items'
  requirements:
    _permission: 'administer site configuration' # @todo review permission
  options:
    _admin_route: TRUE
