<?php

/**
 * @file
 * Contains production_checklist.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\production_checklist\ProductionChecklistInterface;

/**
 * Implements hook_help().
 */
function production_checklist_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the production_checklist module.
    case 'help.page.production_checklist':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A checklist for site launch and maintenance based on the active configuration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function production_checklist_theme() {
  return [
    'project_status_link' => [
      // @todo preprocess hook
      'variables' => [
        'link' => NULL,
        'status' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_checklistapi_checklist_info().
 */
function production_checklist_checklistapi_checklist_info() {
  $definitions = [];
  // Set checklist basic definition.
  $definitions[ProductionChecklistInterface::CHECKLIST_ID] = [
    '#title' => t('Production Checklist'),
    '#path' => 'admin/config/production_checklist/checklist',
    '#callback' => 'production_checklist_checklistapi_checklist_items',
    '#description' => t('Production environment checklist. Happiness is in ticking boxes.'),
  ];
  return $definitions;
}

/**
 * Implements callback_checklistapi_checklist_items().
 */
function production_checklist_checklistapi_checklist_items() {
  // @todo add basic / extended checklist filter
  // @todo add launch / maintenance checklist filter
  // @todo notification once a checked item has been invalidated by configuration
  // @todo convert formUserInput into fromRoute

  /** @var \Drupal\production_checklist\ProductionChecklistInterface $productionChecklist */
  $productionChecklist = \Drupal::service('production_checklist');
  return $productionChecklist->getAvailableSectionsItems();
}

/**
 * Implements hook_checklistapi_checklist_info_alter().
 */
function production_checklist_checklistapi_checklist_info_alter(array &$definitions) {
  /** @var \Drupal\Core\Render\Renderer $renderer */
  $renderer = \Drupal::service('renderer');

  // Set configuration Url in info_alter, once the route is available.
  $configurationUrl = Url::fromRoute('production_checklist.sections');
  $configurationLink = Link::fromTextAndUrl(t('Configure available sections'), $configurationUrl);
  $configurationLink = $configurationLink->toRenderable();
  $configurationLink = $renderer->renderRoot($configurationLink);
  $definitions[ProductionChecklistInterface::CHECKLIST_ID]['#help'] = '<p>'
    . t('A checklist for site launch and maintenance based on the active configuration. @config_link.',
    ['@config_link' => $configurationLink]) . '</p>';

  /** @var \Drupal\production_checklist\ProductionChecklistInterface $productionChecklist */
  $productionChecklist = \Drupal::service('production_checklist');
  /** @var \Drupal\Core\Config\ImmutableConfig $config */
  $config = \Drupal::config('production_checklist.settings');

  // Remove sections that are unset from the configuration.
  $configuredSections = $config->get('sections');
  foreach ($definitions[ProductionChecklistInterface::CHECKLIST_ID] as $sectionKey => $sectionTitle) {
    if (!array_key_exists($sectionKey, $productionChecklist->getAvailableSections())
      || (isset($configuredSections[$sectionKey]) &&  $configuredSections[$sectionKey] === 0)) {
      if (strpos($sectionKey, '#') === FALSE) {
        unset($definitions[ProductionChecklistInterface::CHECKLIST_ID][$sectionKey]);
      }
    }
  }
}
