production_checklist.checklist:
  title: 'Production Checklist'
  parent: system.admin_config_development
  route_name: checklistapi.checklists.production_checklist
  description: 'Production Checklist'

production_checklist.settings:
  title: 'Production Checklist settings'
  route_name: production_checklist.settings
  description: 'Notification preferences.'
  parent: production_checklist.checklist
  weight: 99

production_checklist.sections:
  title: 'Production Checklist sections'
  route_name: production_checklist.sections
  description: 'Sections to enable and notification preferences.'
  parent: production_checklist.checklist
  weight: 99
