<?php

/**
 * @file
 * Contains production_checklist.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function production_checklist_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the production_checklist module.
    case 'help.page.production_checklist':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A checklist for site launch and maintenance based on the active configuration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function production_checklist_theme() {
  return [
    'project_status_link' => [
      // @todo preprocess hook
      'variables' => [
        'link' => NULL,
        'status' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_checklistapi_checklist_info().
 */
function production_checklist_checklistapi_checklist_info() {
  // @todo add basic / extended checklist filter
  // @todo add launch / maintenance checklist filter
  // @todo uncheck and log once status has evolved
  // @todo check Coder Review, Advagg
  // @todo convert formUserInput into fromRoute

  /** @var \Drupal\production_checklist\ProductionChecklistInterface $productionChecklist */
  $productionChecklist = \Drupal::service('production_checklist');
  $definitions = [];
  $definitions['production_checklist'] = [
    '#title' => t('Production Checklist'),
    '#path' => 'admin/config/production_checklist/checklist',
    '#description' => t('Production environment checklist. Happiness is in ticking boxes.'),
    '#help' => t('<p>A checklist for site launch and maintenance based on the active configuration.</p>'),
    // Drupal system check.
    'drupal_system' => [
      '#title' => t('Drupal system'),
      '#description' => t('System wide status and reports.'),
      'status_report' => [
        '#title' => t('Review status report'),
        '#description' => t('Contains general system information.'),
        'path' => [
          '#text' => t('Status report'),
          '#url' => Url::fromUserInput('/admin/reports/status'),
        ],
      ],
      'site_information' => [
        '#title' => t('Site information'),
        '#description' => t('Make sure the email address and site name are correct. Check the homepage title.'),
        'path' => [
          '#text' => t('Basic site settings'),
          '#url' => Url::fromUserInput('/admin/config/system/site-information'),
        ],
      ],
      'recent_logs' => [
        '#title' => t('Review recent logs'),
        // @todo add service for log errors based on a config threshold
        '#description' => t('Monitor your site or debug site problems.'),
        'path' => [
          '#text' => t('Recent log messages'),
          '#url' => Url::fromUserInput('/admin/reports/dblog'),
        ],
      ],
      'error_display' => [
        '#title' => t('Disable error display'),
        // @todo add service for log errors based on a config threshold
        '#description' => t('Disable any errors output on frontend.'),
        'path' => [
          '#text' => t('Logging and errors'),
          '#url' => Url::fromUserInput('/admin/config/development/logging'),
        ],
      ],
      'core_search' => [
        '#title' => t('Core search'),
        '#description' => t('Disable core search if unused or if a replacement search is used (Search API, ...).'),
        'path' => [
          '#text' => t('Logging and errors'),
          '#url' => Url::fromUserInput('/admin/config/development/logging'),
        ],
      ],
      'syslog' => [
        '#title' => t('Enable Syslog core module and optionally disable Database Logging for performance.'),
        '#description' => t('Logs and records system events to syslog.'),
        // @todo check modules status
        'path' => $productionChecklist->getModulesPageTextUrl(),
      ],
    ],
    // Drupal codebase.
    'drupal_codebase' => [
      '#title' => t('Drupal code base'),
      '#description' => t('Review contributed projects: core, modules and themes.'),
      'development_modules' => [
        '#title' => t('Uninstall development modules'),
        // @todo if all modules uninstalled, skip modules page link.
        '#description' => $productionChecklist->getDevelopmentModulesStatusLink(),
        'path' => $productionChecklist->getModulesUninstallPageTextUrl(),
      ],
      'unused_modules' => [
        '#title' => t('Unused modules'),
        '#description' => 'Uninstall and remove unused modules.',
        'path' => $productionChecklist->getModulesUninstallPageTextUrl(),
      ],
      'unused_themes' => [
        '#title' => t('Unused themes'),
        '#description' => 'Uninstall and remove unused themes.',
        'path' => [
          '#text' => t('Select and configure themes'),
          '#url' => Url::fromRoute('system.theme_install'),
        ],
      ],
    ],
    // Other codebase.
    'other_codebase' => [
      '#title' => t('Other code base'),
      '#description' => t("<p>Vendors, custom code and libraries</p>"),
      'development_vendors' => [
        '#title' => t('Remove development vendors like PHPUnit, Behat.'),
        '#description' => t('Run <code>composer install --no-dev</code>'),
        'documentation' => [
          '#text' => t('Composer install documentation'),
          '#url' => Url::fromUri(t('https://getcomposer.org/doc/03-cli.md#install')),
        ],
      ],
      'custom_libraries' => [
        '#title' => t('Remove unused libraries'),
        '#description' => t('Check the /libraries directory'),
      ],
      'node_modules' => [
        '#title' => t('Node modules'),
        '#description' => t('Check if Node modules dedicated to SASS build, ... are not in the codebase.'),
      ],
      'phpmd' => [
        '#title' => t('PHP Mess Detector'),
        '#description' => t('Run PHP Mess Detector on custom code.'),
        'documentation' => [
          '#text' => t('PHP Mess Detector'),
          '#url' => Url::fromUri(t('https://phpmd.org/')),
        ],
      ],
      'phpcs' => [
        '#title' => t('PHPCS'),
        '#description' => t('Run the <code>phpcs</code> command on custom code.'),
        'documentation' => [
          '#text' => t('PHP Coding Standards'),
          '#url' => Url::fromUri(t('https://www.drupal.org/docs/develop/standards/coding-standards')),
        ],
      ],
    ],
    // Spam prevention.
    'spam_prevention' => [
      '#title' => t('Spam prevention'),
      '#description' => t('Configuration and modules related to spam.'),
      'user_registration' => [
        '#title' => t('Review user registration'),
        // @todo add service for current setting
        '#description' => t('Depending on the use case, new account creations can be reserved to administrators.'),
      ],
      'content_permissions' => [
        '#title' => t('Check permissions for <em>content</em> creation'),
        '#description' => t('Node related permissions.'),
      ],
      'comment_permissions' => [
        '#title' => t('Check permissions for <em>comment</em> creation'),
        '#description' => 'Comment related permissions.',
      ],
      'forms' => [
        '#title' => t('Check contact form and webform configuration'),
        '#description' => t('Are the main contact form and personal contact form enabled? Is Webform installed?'),
      ],
      'antispam' => [
        '#title' => t('Are the forms protected with Honeypot and Captcha (and optionally reCaptcha)?'),
        // @todo depend on forms settings
        '#description' => $productionChecklist->getAntiSpamStatusLink(),
      ],
      'email_obfuscation' => [
        '#title' => t('Email obfuscation'),
        '#description' => t('Are the email addresses protected against bots harvesting? In fields, WYSIWYG, Twig.'),
      ],
    ],
    // Security and access control.
    'security_access' => [
      '#title' => t('Security and access'),
      '#description' => t('This topic can be extended with @site_audit_link, @security_review_link @todo add other modules. Basically, test simultaneous and consequent anonymous access scenarios and behavior when every cache is enabled.',
       [
         '@site_audit_link' => '@todo site audit',
         '@security_review_link' => '@todo security review',
       ]
      ),
      'security_update' => [
        '#title' => t('Drupal and other projects update'),
        // @todo add on service
        '#description' => t('Are all the security updates applied?'),
      ],
      'permission' => [
        '#title' => t('Review the permissions'),
        '#description' => t('This should be done for each role.'),
      ],
      'input_format' => [
        '#title' => t('Input format'),
        '#description' => t('Make sure that input formats are correctly configured. <em>Full HTML</em> should be avoided for untrusted users.'),
      ],
      'password' => [
        '#title' => t('Check passwords'),
        '#description' => t('Depending on the role, passwords should be hard to guess. Use a module like Password Policy.'),
        'password_policy' => [
          '#text' => t('Password Policy'),
          '#url' => Url::fromUri('https://www.drupal.org/project/password_policy'),
        ],
      ],
      'access_denied' => [
        '#title' => t('Review access denied errors'),
        '#description' => t('If needed block IP addresses with the core Ban module. This process can be completed with the recent log messages'),
        'path' => [
          '#text' => t('Top access denied errors'),
          '#url' => Url::fromUserInput('/admin/reports/access-denied'),
        ],
      ],
      'changelog' => [
        '#title' => t('Changelog'),
        '#description' => t('Do not publish CHANGELOG.txt'),
      ],
      'staging_local' => [
        '#title' => t('Staging and dev environments'),
        '#description' => t('Make sure that your staging and dev environments does not contain sensitive data.'),
        'documentation' => [
          '#text' => t('Securing Non-Production Environments'),
          '#url' => Url::fromUri('https://dev.acquia.com/blog/securing-nonproduction-environments/09/03/2018/19251'),
        ],
      ],
    ],
    // Content model and content.
    'content' => [
      '#title' => t('Content'),
      '#description' => t('Content model review and proofreading'),
      'content_model' => [
        '#title' => t('Review content model'),
        '#description' => t('Remove unused content types, vocabularies, roles, fields, ...'),
      ],
      'dummy_content' => [
        '#title' => t('Remove dummy content'),
        '#description' => t('Content, terms, users, ... dedicated to site building (e.g. devel generate, ...) should not be there.'),
      ],
      'forms_test' => [
        '#title' => t('Remove forms tests'),
        '#description' => t('Webform provides a test deletion tab for each webform.'),
      ],
      'files' => [
        '#title' => t('Files sub directories'),
        '#description' => t('Configure file and media fields for storing files in sub directories instead of /files.'),
      ],
    ],
    // Frontend.
    'frontend' => [
      '#title' => t('Frontend'),
      '#description' => t('Frontend minimal requirements'),
      'maintenance_page' => [
        '#title' => t('Provide a maintenance page'),
        '#description' => t('@todo'),
      ],
      'not_found' => [
        '#title' => t('Provide a 404 page'),
        '#description' => t('@todo'),
      ],
      'favicon' => [
        '#title' => t('Favicon'),
        '#description' => t('@todo.'),
      ],
    ],
    // Database and configuration.
    'database' => [
      '#title' => t('Database and configuration'),
      'db_update' => [
        '#title' => t('Check database update'),
        '#description' => t('Run /update.php'),
      ],
      'entity_update' => [
        '#title' => t('Check entity update'),
        '#description' => t('Run <code>drush entup</code>'),
      ],
      'configuration_export' => [
        '#title' => t('Export current configuration'),
        '#description' => t('Run <code>drush cex</code>'),
      ],
    ],
    // Performance
    // - @todo Varnish
    // - @todo Memcached.
    'performance' => [
      '#title' => t('Performance'),
      '#description' => t('Performance and caching configuration. To go deeper, consider Performance and Scalability Checklist.'),
      'caching' => [
        '#title' => t('Caching'),
        '#description' => t('Are page caching and CSS/JS aggregation enabled? /admin/config/development/performance'),
      ],
      'big_pipe' => [
        '#title' => t('BigPipe'),
        '#description' => t('Consider enabling the BigPipe module.'),
        'path' => $productionChecklist->getModulesPageTextUrl(),
      ],
    ],
    'test' => [
      '#title' => t('Testing'),
      '#description' => t('Test coverage with BDD (Behat), PHPUnit, ... @todo references.'),
      'manual_test' => [
        '#title' => t('Manual test'),
        '#description' => t('Test the website for each role, anonymous included. Test with caches enabled. Use Masquerade to substitute as other users.'),
        'masquerade' => [
          '#text' => t('Masquerade module'),
          '#url' => Url::fromUri(t('https://drupal.org/project/masquerade')),
        ],
      ],
      'behat' => [
        '#title' => t('Run Behat tests'),
        '#description' => t('@todo'),
        '#text' => t('Behat'),
        '#url' => Url::fromUri(t('http://behat-drupal-extension.readthedocs.io/en/3.1/intro.html')),
      ],
      'php_unit' => [
        '#title' => t('Run PHPUnit tests'),
        '#description' => t('@todo'),
        '#text' => t('PHP Unit'),
        '#url' => Url::fromUri(t('https://www.drupal.org/docs/8/phpunit')),
      ],
    ],
    'analytics' => [
      '#title' => t('Analytics'),
      '#description' => t('External tools to measure audience.'),
      'google_analyics' => [
        '#title' => t('Google Analytics'),
        '#description' => t('Is Google Analytics installed and configured?'),
        '#text' => t('Google Analytics module'),
        '#url' => Url::fromUri('https://www.drupal.org/project/google_analytics'),
      ],
      'google_webmaster_tools' => [
        '#title' => t('Google webmaster tools'),
        '#description' => t('Are Google webmaster tools configured?'),
      ],
      'heatmap' => [
        '#title' => t('Heatmap'),
        '#description' => t('Is Hotjar or another heatmap installed and configured?'),
        'hotjar' => [
          '#text' => t('Hotjar'),
          '#url' => Url::fromUri('https://www.hotjar.com/'),
        ],
      ],
    ],
    // Sysadmin check.
    'sysadmin' => [
      '#title' => t('Sysadmin and backups'),
      '#description' => t('Server configuration and backups'),
      'backup' => [
        '#title' => t('Backups'),
        '#description' => t('Make sure that you have database and files backups enabled. Use a module like Backup and Migrate with Nodesquirell.'),
      ],
      'mail' => [
        '#title' => t('Mails'),
        '#description' => t('Have mails being tested for each form (e.g. password reset). Is a third party needed? Are SPF and PTR ok?'),
      ],
      'ssl' => [
        '#title' => t('SSL certificate'),
        '#description' => t("Free SSL certificates are available from Let's Encrypt."),
      ],
      'max_upload' => [
        '#title' => t('Maximum file upload size'),
        '#description' => t("This should be set in your per vhost php.ini configuration if available."),
      ],
      'file_permission' => [
        '#title' => t('Check files/directorys permissions and ownership'),
        '#description' => t('Usually one owner per virtual host, files at 644 and directories at 755.'),
      ],
      'cron_job' => [
        '#title' => t('Check cron jobs'),
        '#description' => t('Modules like Scheduler should work properly. If you have custom cron jobs, check if your system cron is executed on startup and configured properly for your user.'),
        // @todo check if Automated Cron is enabled
      ],
      'load' => [
        '#title' => t('Check server load'),
        '#description' => t('Will your server support peaks?'),
      ],
      'reverse_proxy' => [
        '#title' => t('Reverse proxy'),
        '#description' => t('If your production server uses a proxy or load balancer, configure it in your settings.php.'),
      ],
    ],
    // Basic SEO.
    'seo' => [
      '#title' => t('SEO'),
      '#description' => t('Basic SEO. To go deeper, use SEO Checklist.'),
      'url_rewriting' => [
        '#title' => t('URL rewriting'),
        '#description' => t('Is URL rewriting enabled and Pathauto configured?'),
      ],
      'not_found' => [
        '#title' => t('Review 404 errors'),
        '#description' => t('Consider using the Redirect module.'),
        'path' => [
          '#text' => t("Top 'page not found' errors"),
          '#url' => Url::fromUserInput('/admin/reports/page-not-found'),
        ],
      ],
      'htaccess' => [
        '#title' => t('Review your .htaccess'),
        '#description' => t('There should be a single version of your site, redirect non www prefix to www (or the opposite) and http to https.'),
      ],
      'robots' => [
        '#title' => t('Review your robots.txt'),
        '#description' => t('Especially if some paths should be excluded.'),
      ],
      'sitemap' => [
        '#title' => t('Sitemap'),
        '#description' => t('Configure your sitemap.xml with a modules like Simple Sitemap.'),
        'simple_sitemap' => [
          '#text' => t('Simple Sitemap module'),
          '#url' => Url::fromUri('https://drupal.org/project/simple_sitemap'),
        ],
      ],
      'submit_url' => [
        '#title' => t('Submit the URL'),
        '#description' => t('For new sites only.'),
        'google_submit' => [
          '#text' => t('Submit URL to Google'),
          '#url' => Url::fromUri('https://www.google.com/webmasters/tools/submit-url'),
        ],
      ],
    ],
    // Legal.
    'legal' => [
      '#title' => t('Legal'),
      '#description' => t('Legal aspects'),
      'cookie_control' => [
        '#title' => t('Cookie compliance with regulations'),
        '#description' => t('@todo'),
        'project' => [
          '#text' => t('Cookie control module'),
          '#url' => Url::fromUri('https://www.drupal.org/project/cookiecontrol'),
        ],
      ],
      'conditions' => [
        '#title' => t('Privacy policy and general conditions'),
        '#description' => t('@todo review commerce use case'),
      ],
      'gdpr' => [
        '#title' => t('GDPR'),
        '#description' => t('Check compliance with the General Data Protection Regulation.'),
        'project' => [
          '#text' => t('GDPR module'),
          '#url' => Url::fromUri('https://drupal.org/project/gdpr'),
        ],
      ],
    ],
    // Project documentation.
    'documentation' => [
      '#title' => t('Project documentation'),
      '#description' => t('@todo'),
      'author_documentation' => [
        '#title' => t('Author documentation'),
        '#description' => t('@todo'),
      ],
      'developer_documentation' => [
        '#title' => t('Developer onboarding'),
        '#description' => t('@todo'),
      ],
    ],
    // Go deeper with specialized modules or services
    // use it in the context
    // - Acquia Insight
    // - YSlow
    // - Google page speed
    // - Profilers (XHProf, Blackfire), monitoring (MRTG, New Relic, ...)
  ];

  return $definitions;
}
